name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: yarn install
      - name: Prepare Integration
        run: ./integration/pbjs.sh
      - name: Codegen
        run: yarn proto2ts
      # This will fail if any git-tracked file have changed
      - name: Diff Output
        run: |
          git add .
          git status && git diff --cached --exit-code
      - name: test
        run: yarn test
        env:
          CI: true
      - name: test esmodule interop
        working-directory: ./integration/simple-esmodule-interop
        run: |
          yarn install
          yarn tsc
          yarn jest
        env:
          CI: true
